version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chat-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-69mg00np2x5n"
s3_prefix = "chat-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_connections\" TableNameRooms=\"simplechat_rooms\""
