/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:90358135-df78-458a-8d6b-5cae264bf2d6",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ipR1JOO5N",
    "aws_user_pools_web_client_id": "2fjp3isp49m23f68hmpmts51si",
    "oauth": {}
};


export default awsmobile;
